service: simplest-hello-world

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
functions:
  simpleHelloWorld:
    handler: handler.simplestHelloWorld
    events:
      - http:
          path: my-nodejs-service
          method: get
          cors: false
